# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: message.proto
# Protobuf Python Version: 5.28.2
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    5,
    28,
    2,
    '',
    'message.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\rmessage.proto\"\x98\x02\n\x0b\x43hatMessage\x12\x0f\n\x07latency\x18\x01 \x01(\x02\x12\x14\n\x0cperf_test_id\x18\x02 \x01(\x05\x12\x10\n\x08\x63pu_load\x18\x03 \x03(\x02\x12\x14\n\x0cmemory_usage\x18\x04 \x01(\x02\x12\x1a\n\x12\x61\x63tive_connections\x18\x05 \x01(\x05\x12\x16\n\x0emessage_volume\x18\x06 \x01(\x05\x12\x11\n\tmv_period\x18\x07 \x01(\x02\x12\x13\n\x0bmv_adjusted\x18\x08 \x01(\x05\x12\r\n\x05\x65vent\x18\t \x01(\t\x12\x0e\n\x06sender\x18\n \x01(\t\x12\x0f\n\x07sent_at\x18\x0b \x01(\t\x12\x0f\n\x07\x63hannel\x18\x0c \x01(\t\x12\x0f\n\x07\x63ontent\x18\r \x01(\t\x12\x0c\n\x04\x64\x61ta\x18\x0e \x03(\tb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'message_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_CHATMESSAGE']._serialized_start=18
  _globals['_CHATMESSAGE']._serialized_end=298
# @@protoc_insertion_point(module_scope)
