services:
  chattr_server:
    image: ${CHATTR_IMAGE}
    container_name: chattr
    # build: .
    env_file:
      - .env
    restart: unless-stopped
    volumes:
      - ./src:/app # Mount the current directory to /app in the container
      - ./db_data:/app/services/db_data # Mount the db_data directory on the host to the services directory in the container

    ports:
      - "127.0.0.1:7999:7999"
    command: uvicorn main_server:app --host 0.0.0.0 --port 7999
    # command: tail -f /dev/null # Keep the container running with no process

volumes:
  db_data:
  src:
